language: php
sudo: false
php:
  - 5.6
#  - 7.0
#  - hhvm
#  - nightly
env:
  - ext=no
  - ext=memcache
  - ext=memcached
services:
  - memcached
before_install:
  - if [[ $ext = 'memcache' ]]; then echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ $ext = 'memcached' ]]; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
install:
  - composer install
script: vendor/bin/phpunit --testdox
