language: php
sudo: false
php:
  - 5.6
  - 7.0
  - hhvm
  - nightly
services:
  - memcached
before_install:
  - echo $TRAVIS_PHP_VERSION
  - phpenv config-rm xdebug.ini
install:
  - composer install
#before_script:
#  - phpenv config-add xdebug.ini
#  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
