language: php
php:
  - 5.6
  - 7.0
  - hhvm
  - nightly
services:
  - memcached
before_install:
  - phpenv config-rm xdebug.ini
install:
  - composer install
  - sudo apt-get -y install php-memcache php-memcached
